#!/usr/bin/env ruby

# frozen_string_literal: true

require 'docopt'
require 'nokogiri'
require 'open-uri'

docs = <<~DOC
  Fetch CSS

  Usage:
    #{__FILE__} <url>
DOC

def main(url)
  doc = Nokogiri.HTML(URI.parse(url).open)
  stylesheets = doc.css('link[rel="stylesheet"],style')
  stylesheets.each do |stylesheet|
    case stylesheet.name
    when "link"
      puts URI.parse(stylesheet['href']).open.read
    when "style"
      if not stylesheet['id'] =~ /criticalCss|cssHide/
        puts stylesheet.content
      end
    else
      die "Unexpected node type"
    end
  end
end

begin
  opts = Docopt.docopt(docs)
  main opts['<url>']
rescue Docopt::Exit => e
  puts e.message
  exit 1
end
