#!/usr/bin/env ruby

# frozen_string_literal: true

require 'docopt'
require 'nokogiri'
require 'open-uri'

docs = <<~DOC
  Fetch CSS

  Usage:
    #{__FILE__} <url>
DOC

def main(url)
  document = Nokogiri.HTML(URI.parse(url).open)

  critical_css = document.css('link[rel="stylesheet"],style')
    .reject { |s| s['media'] == 'print' }
    .reject { |s| s['id'] =~ /criticalCss|cssHide/ }

  critical_css.each do |stylesheet|
      case stylesheet.name
      when 'link'
        puts URI.parse(stylesheet['href']).open.read
      when 'style'
        puts stylesheet.content
      else
        die 'Unexpected node type'
      end
  end
end

begin
  opts = Docopt.docopt(docs)
  main opts['<url>']
rescue Docopt::Exit => e
  puts e.message
  exit 1
end
